### ISSUE TITLE
No longer works with API 2.0

### ISSUE THREAD

**Issue by Azonind** [jensb89/trakt---letterboxd-import#1]
I just get these errors when I try run the script: http://paste.ubuntu.com/11297096/

Will this script be updated at any point to support the new API?

Thanks

**Comment by jensb89** [comment]
Hi, 
sry for the late reply, I haven't been very active on Github the last time.
The errors are due to the new API.
I just started on changing the script to the new API, I already have a working example on my disc, but the code is not ready for public ;)
I will upload a working version soon :)
