### ISSUE TITLE
Netflix.csv Import

### ISSUE THREAD

**Issue by Captain-Wiggles** [jensb89/trakt---letterboxd-import#13]
I apologize if this is the wrong section to request but I am not too familiar with github and had stumbled upon this tool.

Is it possible to add a branch to import netflix.csv files to trakt?

I looked at the letterbox'd import lists and saw that it's very similar to the netflix.csv and was going to try and import via that but figured I'd ask before trying and messing anything up.

**Comment by jensb89** [comment]
No need for a branch, I already have another reposity for importing Netflix Csv files to trakt :) 

Check out the following repo:
https://github.com/jensb89/Netflix-to-Trakt-Import
