### ISSUE TITLE
Where in the Python file do I fill in `$ python py-trakt-letterboxd-import.py diary.csv`

### ISSUE THREAD

**Issue by MikevE1995** [jensb89/trakt---letterboxd-import#19]
I've opnened the file in PyCharm but I have no idea where to put the following line: `$ python py-trakt-letterboxd-import.py diary.csv`

Also which of the 2 files do I need to use?
py-trakt-letterboxd-import or py-trakt-letterboxd-import-python3?

**Comment by MikevE1995** [comment]
gettting all type of errors when trying to run the programm:

Authentication with Trakt.tv....
Authentication File not found!
 Trying first authentication ...
Traceback (most recent call last):
  File "C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py", line 81, in authorize
    r = urllib2.urlopen(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py", line 212, in <module>
    token = check_authentication()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py", line 44, in check_authentication
    authorize(CODE)
  File "C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py", line 89, in authorize
    raise Exception("Bad Request - request couldn't be parsed")
Exception: Bad Request - request couldn't be parsed

Process finished with exit code 1

**Comment by jensb89** [comment]
> I've opnened the file in PyCharm but I have no idea where to put the following line: `$ python py-trakt-letterboxd-import.py diary.csv`
> 
> Also which of the 2 files do I need to use? py-trakt-letterboxd-import or py-trakt-letterboxd-import-python3?

Hi,
so the line `$ python py-trakt-letterboxd-import.py diary.csv` means you call the script via python from the command line. The $ sign does not need to be typed in (under linux systems it's already printed usually, under Windows you can ignore it) If you type "python --version" on the command line, you will see which python version you have installed. If it starts with 3 you have to call the python3 script.

The errors from your last reply indicate some problems with the http requests. That means either trakt.tv has changed their API (unlikely), your python version and packages are newer and have changes incompatible with the code,  there are some proxy problems on your end, there is indeed some problem with the code (but there haven't been any other issues raised) or you haven't filled in the cient id and secet. "HTTP Error 400: Bad Request" actually indicates something wrong or missing is sent to the server. 

Have you filled out the following part in the code?

CLIEN_ID= '' #Fill in your client id
CLIEN_SECRECT = '' #Fill in your client secred
CODE = '' #Fill in your code, which you get after authorization with your trakt account

**Comment by MikevE1995** [comment]
I have Python 3.11
I've also filled in the ID, secret and code

I have absolutely no idea what to do now.... do I need to use PyCharm or can I use something else too?

**Comment by MikevE1995** [comment]
I need to know what this part below needs to be:

def usage(argv0):
    print('usage: '+argv0+' [OPTION] FILE ...')
    print(python py-trakt-letterboxd-import.py diary.csv)
    OPTIONS
    -h
    --help          Show help
    --watched       Use watched.csv file instead of diary (no watched date!!)
    --debug         Turn on debuging mode (doesn't exist)
    EXAMPLE USAGE
        python py-trakt-letterboxd-import.py diary.csv
    ''')
    sys.exit(1)

**Comment by jensb89** [comment]
This is just the function that is called when you provide the wrong inputs. It's called in line 200.
As I said, you haven't called the script correctly, the csv file is missing and letterboxd_file is empty then.

**Comment by MikevE1995** [comment]
usage(sys.argv[0])

this is line 200 for me...

**Comment by jensb89** [comment]
yes, that's where the usage() function is called. The usage() function just prints some info to the console.

Except for the ID, secret and token you do not need to change anything in the file. The file is correct!
You have to change your call of the file only.

How do you call the script? Via console? Via this pyCharme program? 
The error is not in the file but in your call.

**Comment by MikevE1995** [comment]
I use the PyCharm programm to run the script

**Comment by jensb89** [comment]
The call is "python <script_name>.py <filepath/filename.csv>"
Hereby <script_name> equals to py-trakt-letterboxd-import or py-trakt-letterboxd-import3. 
You have to provide filepath and filename

**Comment by jensb89** [comment]
> I use the PyCharm programm to run the script

The you have to check out how you can call the script with extra parameters in pyCharm. I do not use pyCharm.

**Comment by MikevE1995** [comment]
C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py

"python py-trakt-letterboxd-import-python3.py C:\Users\mikev\Downloads\trakt---letterboxd-import-master\diary.csv>"

Filled this in the script path and parameter. Still getting the error, what am I doing wrong here?

**Comment by jensb89** [comment]
> "python py-trakt-letterboxd-import-python3.py C:\Users\mikev\Downloads\trakt---letterboxd-import-master\diary.csv"

That looks correct. But I'm afraid I don't know much about pyCharm, there might be some extra settings needed. I work under macOS/Linux directly on the console. I can't help you with pyCharm under Windows, sorry

**Comment by MikevE1995** [comment]
I can maybe run the script on my Synology NAS

**Comment by MikevE1995** [comment]
File "/volume1/MEDIA-VAULT-1/trakt---letterboxd-import-master/py-trakt-letterboxd-import-python3.py", line 185
    --help          Show help
                    ^
SyntaxError: invalid syntax

This is the error im getting now on my NAS. Any idea?

**Comment by jensb89** [comment]
Hm, I'm sorry that it doesn't work for you.
The easiest way to call it is by placing the diary.csv in the same folder, open a console (cmd under windows), go to that folder (cd directory and so on) and call python <script>.py diary.csv. 

The code that reads the filename from the arguments is this:

args, letterboxd_file = getopt.gnu_getopt(sys.argv[1:], 'h:w',['help','watched']) 
That should be system independent.

**Comment by MikevE1995** [comment]
can I use the terminal for that in windows?

**Comment by jensb89** [comment]
> 

Hm, are you sure your NAS python is also version 3?
If yes, that is strange. Maybe really a newer python version expects different call to the getopt.gnu_getopt. There is also another way to get the file name in python without the getopt call. I will give you an example that you can try in a few minutes

**Comment by jensb89** [comment]
> can I use the terminal for that in windows?

Yes, terminal is fine. Just make sure you can call "python --version"

**Comment by MikevE1995** [comment]
> 

version 3.8.2 on my Windows

**Comment by MikevE1995** [comment]
getting the same syntax notification on my pc

**Comment by jensb89** [comment]
Check out this article: https://www.knowledgehut.com/blog/programming/sys-argv-python-examples#understanding%C2%A0sys.argv%C2%A0with-examples

In short:
You can replace the whole getopt line by this in general:
letterboxd_file = sys.argv[1] and delete the for loop that comes in the except block

That's a little rudimental, there will be no help menu anymore and all. But that's the simplest call available. If you then still get that error then your call definitely does not pass the filename correctly

**Comment by MikevE1995** [comment]
I finally got it working! Re-dwonloaded the python3 file and used the following script:

python C:\Users\mikev\Downloads\trakt---letterboxd-import-master\py-trakt-letterboxd-import-python3.py C:\Users\mikev\Downloads\trakt---letterboxd-import-master\diary.csv

Thank you for your help (and patience haha)!

**Comment by jensb89** [comment]
No problem, I'm glad it works for you :)
