### ISSUE TITLE
Make this script also work with the watched.csv?

### ISSUE THREAD

**Issue by kellertuer** [jensb89/trakt---letterboxd-import#2]
Hi there,
thanks very much for this nice script! I already imported my diary. Could you adapt this script or provide a second one to also upload the watched.csv? I' getting the error

>Traceback (most recent call last):
>  File "py-trakt-letterboxd-import.py", line 185, in <module>
>    data = get_data_letterboxd_diary(letterboxd_file[0])
>  File "py-trakt-letterboxd-import.py", line 115, in get_data_letterboxd_diary
>    data.append([row[1],row[2],row[6]+' 20:15',imdbid])
>IndexError: list index out of range`

and i think it's due to a missing element [6], because of course the watched ones not necessarily have a date when they have been watched by me.

**Comment by jensb89** [comment]
The import of the watched.csv can now be used by adding the --watched option, I updated the readme as well :)
