### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Djeezas** [jensb89/trakt---letterboxd-import#22]
Hi, I don't know much about code and I'm kinda confused as to what Step 4 is supposed to be. What is "$ python py-trakt-letterboxd-import.py diary.csv" and how am I supposed to use it? 
Thank you

**Comment by 4Learnin** [comment]
1. Open the downloaded code folder. 
2. In the folder address bar, type "cmd" and hit enter
3. You will see a black command line window. Now paste this line of code "python py-trakt-letterboxd-import.py diary.csv"  there and hit enter. That's it.

**Comment by Djeezas** [comment]
Thank you, but I now get this error in the command prompt: 
print 'Authentification expired, trying to re-authentificate...'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by Djeezas** [comment]
Nevermind, it worked, thank you very much !
