### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by mikejolema** [jensb89/trakt---letterboxd-import#6]
ValueError: invalid literal for int() with base 10: ''

![screen shot 2018-01-13 at 1 48 24 pm](https://user-images.githubusercontent.com/35405802/34909045-7b8e0286-f868-11e7-8c3f-f8a3b066b36c.png)

**Comment by mikejolema** [comment]
My solution was to go through manually and remove rows that didn't contain a date for the entry. Ideally the script should just skip entries without an associated year.

**Comment by jensb89** [comment]
Thanks for opening the issue. I will look into it and fix it as soon as I find the time :)
